turbolinks/turbolinks

src/turbolinks/controller.coffee
src/turbolinks/view.coffee
test/src/fixtures/rendering.html
test/src/modules/rendering_tests.coffee

The `turbolinks:before-render` event fires just after Turbolinks creates the new body element but before it imports permanent elements. The new body is exposed as `event.data.newBody`.
This gives the application and third-party libraries a chance to query or manipulate the current and new body elements just before the new body is installed.

Add `turbolinks:before-render` event

---

src/turbolinks/controller.coffee
test/src/modules/visit_tests.coffee

* Renames the cancelable `turbolinks:visit` event to `turbolinks:before-visit`.
* Adds an uncancelable `turbolinks:visit` event, fired immediately after any visit starts.

Revised visit events

---

src/turbolinks/view.coffee

Switches to `Element.setAttribute()` and `removeAttribute()` in favor of using `Element.dataset`, which [isn't supported in IE < 11](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes#Issues).
Fixes #21

Use Element.set/removeAttribute() for IE10 compat. Fixes #21

---

src/turbolinks/controller.coffee
src/turbolinks/snapshot.coffee
src/turbolinks/visit.coffee

The motivation of this PR is to explore a way to fix #7.
Upgrading an application to use this new version of Turbolinks, we found a few situations where loading the cached version when visiting a new page is not working fine. In our case, we would like to skip loading the cached version in two cases:
- We don't want to show data entered by users when visiting again a page with a form
- We also have permalinks to sections where a modal dialog is opened. The animation triggers twice in those cases.
I couldn't find in the API any way to deal with this cases. I'm aware that taking advantage of the `turbolinks:before-cache` event could be used to solve the form issue, e.g. clearing the form at this point. However, I didn't know how to fix the animation problem without adding this option.
Even …

Add option to skip cache version in links

---

src/turbolinks/http_request.coffee

This is to fix issue #40 so `format.xml` from within a **respond_to** block doesn't override all other response types.

Remove 'application/xml' from Request Header

---

src/turbolinks/browser_adapter.coffee

Tests still pass, LMK if this breaks things. 
Chrome Timeline *after* this patch - network requests begin 20ms earlier.

Start HTTP request before changing browser history

---

src/turbolinks/controller.coffee
src/turbolinks/view.coffee

Tested on a 4,000-element DOM.
[Before and after](http://imgur.com/a/1JvnJ) - about ~50ms saved.
I'm not sure if these are really necessary - tests still pass, correct me if I'm wrong here.

Remove unneccessary clones

---

README.md

The following line in the current instructions to install Turbolinks [using Webpack](https://github.com/turbolinks/turbolinks#installation-using-webpack) assumes that you already have the `imports-loader` for Webpack installed:
```
module: {
loaders: [ ...,
{ test: require.resolve('turbolinks'), loader: 'imports?this=>window' },
],
}
```
That is a key part of making Turbolinks work with Webpack, because it is what sets the `window` object as the global scope. Therefore I think it is worth making this dependency explicit.

Add missing dependency to Webpack installation instructions

---

src/turbolinks/controller.coffee
src/turbolinks/error_renderer.coffee
src/turbolinks/renderer.coffee
src/turbolinks/snapshot.coffee
src/turbolinks/snapshot_cache.coffee
src/turbolinks/snapshot_renderer.coffee
src/turbolinks/view.coffee

This PR makes cloning the snapshots a concern of the Controller. 
Previously, cloning was performed as-needed in several locations. This PR clones all snapshots as they enter and leave the cache. This has a beneficial side-effect of removing unnecessary cloning during rendering when the Snapshot is not cacheable. 
[Before and after, tested on a 4,000-element DOM.](http://imgur.com/a/pl13b) If the response is not cacheable, this PR eliminates a costly ~70ms of `cloneNode` time when rendering the response.
In addition:
* delegate `isCacheable` to the Snapshot to make it similar to how Previews work
* `getSnapshot` no longer needs to know how to clone snapshots
* Reduce areas in the code that need to know about cloning
* Rename Cache to SnapshotCache, to more accurately reflect what it does.

Make cloning a cache-level concern, speed up non-cacheable responses

---

Gemfile
Gemfile.lock
README.md
src/turbolinks/controller.coffee
src/turbolinks/index.coffee
src/turbolinks/start.coffee

Define UMD module for Turbolinks to support script / module build tools like webpack, browserify, require.js, etc.

Add UMD support. Fixes #91

---

src/turbolinks/controller.coffee
test/src/fixtures/navigation.html
test/src/modules/navigation_tests.coffee

The `href` property of an SVG <a> element is an `SVGAnimatedString` (not a `String`). This prevented it from being extracted by `Turbolinks.Location`, resulting in a broken link.
Use `Element.getAttribute("href")` to ensure the result is a `String`.

Use `Element.getAttribute()` to get a visitable link's href. Fixes #110

---

README.md

Although the old command was valid, it's now slightly misleading to display this as "in beta", in the README!

Remove reference to "beta" version

---

src/turbolinks/history.coffee
src/turbolinks/index.coffee

Avoid error calling addEventListener in browsers that don't support it

---

src/turbolinks/controller.coffee

Clicking on `<a download="...">` will download linked file on modern browsers.
But currently turbolinks captures and visits linked url, so for example mp4 video will be played in current tab.
This PR fixes it by exclude a tag with download attr.

Fix link with download attr is visited

---

src/turbolinks/helpers.coffee
src/turbolinks/scroll_manager.coffee

Limit `onScroll` to once per animation frame to decrease page reflows (`window.pageXOffset` / `window.pageYOffset` cause them) and improve FPS performance when scrolling.

Throttle scroll handler

---

README.md
src/turbolinks/controller.coffee

When using Turbolinks with the `async` script attribute, Turbolinks may
execute after DOMContentLoaded. To fix this, we only attach a handler
to DOMContentLoaded if the readystate is not "loading" (that is to say,
it is "interactive" or "complete"). Otherwise, we fire the pageLoaded
event immediately without installing the handler.
This changes Turbolinks interaction with `defer` scripts. After this
change, an `async` Turbolinks script may execute *before* `defer`ed
scripts. This is because the browser executes all `defer` scripts *before*
the DOMContentLoaded event. Previously, Turbolinks would always execute
after these scripts, but may now execute before them in some cases
depending on when Turbolinks has finished downloading.

If page is interactive, fire pageLoaded() immediately

---

README.md
src/turbolinks/controller.coffee

Reverts: turbolinks/turbolinks#274
Fixes: https://github.com/turbolinks/turbolinks#278
Reason: https://github.com/turbolinks/turbolinks/issues/278#issuecomment-298930676

Revert "If page is interactive, fire pageLoaded() immediately"

---

src/turbolinks/location.coffee
test/src/fixtures/navigation.html
test/src/fixtures/one.html
test/src/helpers/assert_helpers.coffee
test/src/modules/navigation_tests.coffee

Turbolinks is currently ignoring URLs which include an extension as well as a fragment identifier. This is because it will only handle URLs that point to HTML resources, and in this case, the URL is wrongly interpreted as being non-HTML.
A `Location`'s [`isHTML`](https://github.com/turbolinks/turbolinks/blob/c23dbe1beb0f220ada7f422abbf08943a864066a/src/turbolinks/location.coffee#L36) method returns true if its URL ends with an HTML extension (htm, html, or xhtml), or if it has no extension at all. However, if the URL has an HTML extension _and_ a fragment identifier, `isHTML` will be false because it deems everything after the last `.` to be part of the extension. For example the extension of `http://example.com/index.html#foo` would be `.html#foo`. This does not match any of the …

Improve handling of URLs with extensions and fragment identifiers

---

README.md
src/turbolinks/index.coffee
src/turbolinks/script_warning.coffee

This branch shows an early warning in the console when `document.currentScript` is a child of `<body>`:
Turbolinks is designed for application scripts to live in `<head>`, but best practices from several years ago encouraged folks to put all scripts at the end of `<body>`. That seems to trip people up fairly often.

Warn when loading Turbolinks from a <script> inside <body>

---

src/turbolinks/snapshot_renderer.coffee
src/turbolinks/view.coffee

This is an alternate take on https://github.com/turbolinks/turbolinks/pull/292 that passes `isPreview` instead of mutating snapshots with it.
Fixes #290
Closes #292

Skip autofocusing in preview snapshots

---

README.md
src/turbolinks/browser_adapter.coffee
src/turbolinks/controller.coffee
src/turbolinks/index.coffee

Based on the patch in #124, but delegates the delay to `Controller` instead of reaching into the browser adapter directly.

Add Turbolinks.setProgressBarDelay

---

README.md
src/turbolinks/snapshot.coffee
src/turbolinks/snapshot_renderer.coffee
test/src/fixtures/rendering.html
test/src/fixtures/visit_control_reload.html
test/src/modules/rendering_tests.coffee

Addresses #311 with a new meta tag: 
```html
<meta name="turbolinks-visit-control" content="reload">
```
Visiting a page with this tag will always do a full page reload. The result is the same as visiting a page with mismatched tracked assets.

Add meta tag for opting in to full page reloads

---

test/src/fixtures/navigation.html
test/src/fixtures/one.html
test/src/modules/navigation_tests.coffee

https://github.com/turbolinks/turbolinks/pull/270 added an assertion to test whether Turbolinks scrolls to a given element. This PR uses that to test scrolling to named anchors. The base branch is `scroll-to-named-anchor`, so if merged will become part of https://github.com/turbolinks/turbolinks/pull/348

Add test for scrolling to named anchors

---

src/turbolinks/controller.coffee
src/turbolinks/snapshot.coffee
src/turbolinks/view.coffee
test/src/fixtures/navigation.html
test/src/fixtures/one.html
test/src/modules/navigation_tests.coffee

Alternate take on #175.
`Turbolinks.Visit` also looks for an element matching the location's anchor [when deciding whether to use a cached version of the page](https://github.com/turbolinks/turbolinks/blob/f5f6495f650ab53d49e0e60554021b0472b299ec/src/turbolinks/visit.coffee#L50). This check should support named anchors too. This change ensures we have a single way to get the element for an anchor, for both scrolling and caching.

Support scrolling to named anchors

---

src/turbolinks/renderer.coffee

As noted by @kmmbvnr in https://github.com/turbolinks/turbolinks/issues/282#issuecomment-355731712, setting `async = false` doesn't load dynamically created `<script>`s synchronously, but it *does* ensure that they're loaded in order.

Ensure new <script>s are loaded in order when navigating

---

src/turbolinks/controller.coffee
src/turbolinks/head_details.coffee
src/turbolinks/snapshot.coffee
src/turbolinks/snapshot_renderer.coffee
src/turbolinks/view.coffee
test/src/fixtures/permanent_element.html
test/src/fixtures/rendering.html
test/src/modules/rendering_tests.coffee

This pull request modifies Turbolinks to save a snapshot of the previous page to its cache asynchronously _after_ rendering, which means:
* Pages display more quickly, since the call to `body.cloneNode(true)` no longer happens inside the render frame.
* Stimulus controllers can use their `disconnect()` callbacks to prepare the page for caching.
To understand what’s changed, consider the timeline of the current rendering process:
The rendering process takes place inside a `requestAnimationFrame` callback, a technique which enables Turbolinks to synchronize page replacement and scroll positioning without visual flicker.
Turbolinks dispatches a `turbolinks:before-cache` event just before rendering, which allows applications to [prepare the page for …

Deferred snapshot caching

---

README.md

The new version of the ruby gem (5.1.0) allows using turbolinks without the asset pipeline, as discussed here: https://github.com/turbolinks/turbolinks-rails/pull/18
I think it's important to update this documentation, because installing an older version without the asset pipeline throws an error.

Update gem installation instructions

---

src/turbolinks/error_renderer.coffee

It's expected by the super class: https://github.com/turbolinks/turbolinks/blob/7fb280ad9b66f1aa3e52f0e4db7149ab727c59c2/src/turbolinks/renderer.coffee#L8-L11
Fixes that `event.data.newBody` would be `undefined` in `turbolinks:before-render` events for error pages.

Set newBody property when rendering errors

---

README.md

Since https://github.com/turbolinks/turbolinks/commit/866a29c861b0e0e0625a06189a49e29abd7a344a, [`dist` is ignored](https://github.com/turbolinks/turbolinks/blob/866a29c861b0e0e0625a06189a49e29abd7a344a/.gitignore#L1). This PR fixes the broken link to `dist/turbolinks.js` by unlinking it.

Fix broken link to dist/turbolinks.js

---

src/browser_adapter.ts
src/http_request.ts
src/tests/fixtures/svg
src/tests/visit_tests.ts

Avoid rendering responses without an HTML content type header.

Force a full page load when receiving a non-HTML response

---

src/controller.ts
src/history.ts
src/location.ts
src/tests/async_script_tests.ts
src/tests/fixtures/async_script.html
src/tests/fixtures/async_script_2.html
src/tests/index.ts

This branch fixes [navigation when Turbolinks is loaded with a `<script async>` tag (#447)](#447), introduced with the TypeScript port.
(TypeScript made it possible to remove extraneous defensive calls to `Location.wrap(...)` from the CoffeeScript codebase. In one spot, the old code [passed a location variable to Cache#put which might possibly be `undefined`](https://github.com/turbolinks/turbolinks/blob/c340c42e2ece8c057aec611074971462a6e76c71/src/turbolinks/controller.coffee#L101-L103); TypeScript told me about it during the port, but I chose to [ignore it with a non-null assertion](https://github.com/turbolinks/turbolinks/blob/2f7cd3247f28152458e5f45ff281d8ec7b1f8f47/src/controller.ts#L149). Of course, it turns out I was misremembering how the Controller#pageLoaded method works when …

Fix <script async> navigation

---

LICENSE

Reinstate license (with updated copyright year) that was removed in #445.
Closes #472

Reinstate license

---

src/history.ts

When clicking on a link where Turbolinks is disabled via the `data-turbolinks="false"` annotation the PopStateEvent would have no state. This would result in an `Cannot read property 'turbolinks' of null` error.
It is now handled by doing an early return in that situation.
If we were using TS version 3.7 we could've used optional chaining instead of early return guards.

Handle onPopState when turbolinks is disabled

---

README.md

jQuery wraps events into a home-made event object. This wrapping makes the event.data unavailable. This commit adds a little mention of that fact to help a future developer save time and frustration.

Mention that jQuery's `on` will not see event.data
